/**
 * Import TB_CLASSE
 */
INSERT INTO EDUCACAO.TB_CLASSE (CI_CLASSE, CD_ORIGEM, NM_CLASSE, CD_UNIDADE_TRABALHO, CD_SERIE, CD_PERIODO_LETIVO, CD_TURNO, CD_STATUS_CLASSE, CD_TIPO_CLASSE, CD_USO_CLASSE, NR_CAPACIDADE_LOGICA, FL_LIBERA_LOTACAO, CD_USUARIO, DT_REGISTRO) 
(SELECT EDUCACAO.SEQ_CLASSE.NEXTVAL, C.IDCLASSE, C.NOME, UT.CI_UNIDADE_TRABALHO, C.IDSERIE, C.IDPERIODO_LETIVO, C.IDPERIODO_DO_DIA, C.IDSTATUS_CLASSE, C.IDTIPO_CLASSE, C.IDUSO_CLASSE, C.CAPACIDADE_LOGICA, C.LIBERA_LOTACAO, 232, SYSDATE
   FROM PREFSME_PRD_01.CLASSE C
   JOIN UTIL.TB_UNIDADE_TRABALHO UT ON UT.CD_UNIDADE_TRABALHO_ORIGEM = C.IDESCOLA
   WHERE 1 = 1
   AND C.IDPERIODO_LETIVO >= 130
   AND NOT EXISTS (SELECT * FROM EDUCACAO.TB_CLASSE EC WHERE EC.CI_CLASSE = C.IDCLASSE)
);




/**
 * Import TB_MATRICULA_CLASSE
 */
-- INSERT INTO EDUCACAO.TB_MATRICULA_CLASSE X (X.CI_MATRICULA_CLASSE, X.CD_ORIGEM, X.CD_MATRICULA, X.CD_CLASSE, X.NR_CHAMADA, X.FL_STATUS_ALUNO, X.DT_MOVIMENTACAO, X.DT_INCLUSAO, X.CD_USUARIO, X.DT_REGISTRO)
SELECT R.*, 232, SYSDATE FROM 
(SELECT EDUCACAO.SEQ_MATRICULA_CLASSE, AC.IDALUNO_CLASSE, WM_CONCAT(DISTINCT M.CI_MATRICULA), AC.IDCLASSE, AC.NUMERO_CHAMADA, AC.STATUS_ALUNO, AC.DTMOVIMENTACAO, AC.DTINCLUSAO
           FROM PREFSME_PRD_01.ALUNO_CLASSE AC
           JOIN PREFSME_PRD_01.MATRICULA_ALUNO MA ON MA.IDMATRICULA_ALUNO = AC.IDMATRICULA_ALUNO
           JOIN EDUCACAO.TB_MATRICULA M ON M.CD_ORIGEM = MA.IDMATRICULA_ALUNO AND M.CD_ORIGEM = AC.IDMATRICULA_ALUNO
           JOIN EDUCACAO.TB_CLASSE C ON C.CI_CLASSE = AC.IDCLASSE
           WHERE 1 = 1
           AND MA.IDPERIODO_LETIVO >= 130
           AND NOT EXISTS (SELECT * FROM EDUCACAO.TB_MATRICULA_CLASSE EMC WHERE EMC.CI_MATRICULA_CLASSE = AC.IDALUNO_CLASSE)
           GROUP BY AC.IDALUNO_CLASSE, M.CI_MATRICULA, AC.IDCLASSE, AC.NUMERO_CHAMADA, AC.STATUS_ALUNO, AC.DTMOVIMENTACAO, AC.DTINCLUSAO) R ;

