INSERT INTO TB_PERMISSAO VALUES
    (nextval('seq_permissao') , 'ARQUIVO_PAGAMENTO_R', 'LER ARQUIVO PAGAMENTO');   

INSERT INTO TB_PERMISSAO VALUES
    (nextval('seq_permissao') , 'ARQUIVO_PAGAMENTO_C', 'PROCESSAR ARQUIVO PAGAMENTO');   