INSERT INTO tb_GRUPO_PERMISSAO VALUES
    (3, 'GRUPO_PERMISSAO');

INSERT INTO tb_PERMISSAO VALUES
    (9, 'GRUPO_PERMISSAO_C', 'CRIAR GRUPO PERMISSAO', 3);    
INSERT INTO tb_PERMISSAO VALUES
    (10, 'GRUPO_PERMISSAO_R', 'LER GRUPO PERMISSAO', 3);    
INSERT INTO tb_PERMISSAO VALUES
    (11, 'GRUPO_PERMISSAO_U', 'ATUALIZAR GRUPO PERMISSAO', 3);    
INSERT INTO tb_PERMISSAO VALUES
    (12, 'GRUPO_PERMISSAO_D', 'DELETAR GRUPO PERMISSAO', 3);    

ALTER SEQUENCE seq_permissao RESTART WITH 13;

ALTER SEQUENCE seq_grupo_permissao RESTART WITH 4;
